// Class automatically generated by Dev-C++ New Class wizard

#ifndef CASCIIBOARDRENDER_H
#define CASCIIBOARDRENDER_H

#include "cboardrender.h" // inheriting class's header file

// No description
class CASCIIBoardRender : public CBoardRender
{
	public:
		// class constructor
		CASCIIBoardRender();
		// class destructor
		~CASCIIBoardRender();
		virtual void render(CBoard *board);
};

#endif // CASCIIBOARDRENDER_H

