// Class automatically generated by Dev-C++ New Class wizard

#include "casciiboardrender.h" // class's header file

#include <iostream>

using namespace std;

// class constructor
CASCIIBoardRender::CASCIIBoardRender()
{
	// insert your code here
}

// class destructor
CASCIIBoardRender::~CASCIIBoardRender()
{
	// insert your code here
}

void CASCIIBoardRender::render(CBoard *board)
{
    int xdim,ydim;
    
    board->getDimension(&xdim,&ydim);
    cout << "  ";
    for (int x=1;x<=xdim;x++)
        cout << x << " | ";
    cout << endl;
    for (int y=1;y<=ydim;y++)
    {
        cout << y << " ";
        for (int x=1;x<=xdim;x++)
        {
	  switch (board->get(x,y))
          {
              case CBoard::P1:
                  cout << "o";
                  break;
              case CBoard::P2:
                  cout << "x";
                  break;
              case CBoard::NOTHING:
              default:
                  cout << " ";
          }
          cout << " | ";
        }
        cout << endl;
    }
}    

