// Class automatically generated by Dev-C++ New Class wizard

#ifndef CBOARD_H
#define CBOARD_H

#include <string>

using namespace std;

// No description
class CBoard
{
	public:
	    enum EFicha
	    {
	        P1,P2,NOTHING
	    };
            struct SEstado
            {
                unsigned isfinish:1;
                unsigned isempate:1;
                EFicha winer;
            };
            // class constructor
            CBoard();
            // class destructor
            ~CBoard();
	    void Init();
            void getDimension(int *x,int *y) const;
            void set(EFicha ficha,int x,int y) throw(string);
            enum CBoard::EFicha get(int x,int y) const throw(string);
            SEstado isFinish() const;
	private:
	    EFicha m_Ficha[3][3];
            void verifDimension(int x,int y) const throw(string);
            EFicha winer() const;
            EFicha winer(int x,int y,int dx,int dy) const;
};

#endif // CBOARD_H

