// Class automatically generated by Dev-C++ New Class wizard

#ifndef CBOARDRENDERPRINTTEXT_H
#define CBOARDRENDERPRINTTEXT_H

#include "Board.h" // class's header file
#include "BoardRender.h"

// No description
class CBoardRenderPrintText : public CBoardRender
{
	private:
		int m_Maxx,m_Maxy;

	public:
		CBoardRenderPrintText(int maxx,int maxy);
		~CBoardRenderPrintText();
		void render(CBoard &board,CDebugPrintText2D& printText2d);
};

#endif // CBOARDRENDERPRINTTEXT

