// Class automatically generated by Dev-C++ New Class wizard

#ifndef CBOARDRENDER_H
#define CBOARDRENDER_H

#include "cboard.h" // class's header file

// No description
class CBoardRender
{
	public:
		virtual void render(CBoard *board)=0;
};

#endif // CBOARDRENDER_H

